apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequiredimagepullsecrets
  annotations:
    metadata.gatekeeper.sh/title: "Required imagePullSecrets"
    metadata.gatekeeper.sh/version: 1.1.2
    description: >-
      Requires resources to contain imagePullSecrets.
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredImagePullSecrets
      validation:
        openAPIV3Schema:
          type: object
  targets:
    - target: admission.k8s.gatekeeper.sh
      code:
      - engine: Rego
        source:
          rego: |
            package k8srequiredimagepullsecrets

            violation[{"msg": msg}] {
              not input.review.object.spec.imagePullSecrets
              msg := "you must provide imagePullSecrets on pod"
            }