AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template to create two IAM Roles with permissions and trust relationships.'

Resources:
  BootNodeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'BootNodeRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
  DevOpsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'DevOps-Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'